### PR TITLE
Fix tests build with -no-pie option

### PR DESCRIPTION
**Pull request by yota9**
Since gcc/ld often produces PIE files we need to pass -no-pie option to avoid linking errors for tests.
Vladislav Khmelevsky,
Advanced Software Technology Lab, Huawei

### CODE REVIEW

**Comment by yota9** [comment]
#148 Problem

**Comment by Sameeranjoshi** [comment]
Thanks for the fix.
Unfortunately I get below ICE after this patch.
```
Command Output (stderr):
--
llvm-bolt: /home/sameeran/workspace/toolchain/bolt_development/BOLT/bolt/src/RewriteInstance.cpp:3257: void llvm::bolt::RewriteInstance::mapCodeSections(llvm::RuntimeDyld&): Assertion `TextSection->hasValidSectionID() && ".text section should be valid"' failed.
 #0 0x00005624c26507ac llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/sameeran/workspace/toolchain/bolt_development/BOLT/build/bin/llvm-bolt+0xf7e7ac)
 #1 0x00005624c264e7c4 llvm::sys::RunSignalHandlers() (/home/sameeran/workspace/toolchain/bolt_development/BOLT/build/bin/llvm-bolt+0xf7c7c4)
 #2 0x00005624c264e933 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007fda90ebe520 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x13520)
 #4 0x00007fda903a0081 raise /build/glibc-kSJANG/glibc-2.29/signal/../sysdeps/unix/sysv/linux/raise.c:51:1
 #5 0x00007fda9038b535 abort /build/glibc-kSJANG/glibc-2.29/stdlib/abort.c:81:7
 #6 0x00007fda9038b40f _nl_load_domain /build/glibc-kSJANG/glibc-2.29/intl/loadmsgcat.c:1177:9
 #7 0x00007fda90398b92 (/lib/x86_64-linux-gnu/libc.so.6+0x32b92)
 #8 0x00005624c1a14430 llvm::bolt::RewriteInstance::mapCodeSections(llvm::RuntimeDyld&) (/home/sameeran/workspace/toolchain/bolt_development/BOLT/build/bin/llvm-bolt+0x342430)
 #9 0x00005624c1a14451 llvm::bolt::RewriteInstance::mapFileSections(llvm::RuntimeDyld&) (/home/sameeran/workspace/toolchain/bolt_development/BOLT/build/bin/llvm-bolt+0x342451)
#10 0x00005624c1a41b1d llvm::bolt::RewriteInstance::emitAndLink() (/home/sameeran/workspace/toolchain/bolt_development/BOLT/build/bin/llvm-bolt+0x36fb1d)
#11 0x00005624c1a46418 llvm::bolt::RewriteInstance::run() (/home/sameeran/workspace/toolchain/bolt_development/BOLT/build/bin/llvm-bolt+0x374418)
#12 0x00005624c18af13a main (/home/sameeran/workspace/toolchain/bolt_development/BOLT/build/bin/llvm-bolt+0x1dd13a)
#13 0x00007fda9038cbbb __libc_start_main /build/glibc-kSJANG/glibc-2.29/csu/../csu/libc-start.c:342:3
#14 0x00005624c1906d0a _start (/home/sameeran/workspace/toolchain/bolt_development/BOLT/build/bin/llvm-bolt+0x234d0a)
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /home/sameeran/workspace/toolchain/bolt_development/BOLT/build/bin/llvm-bolt /home/sameeran/workspace/toolchain/bolt_development/BOLT/build/tools/bolt/test/X86/Output/fix-branches-jrcxz.s.tmp.exe -relocs=1 -reorder-blocks=cache+ -print-finalized -o /home/sameeran/workspace/toolchain/bolt_development/BOLT/build/tools/bolt/test/X86/Output/fix-branches-jrcxz.s.tmp.out -data /home/sameeran/workspace/toolchain/bolt_development/BOLT/build/tools/bolt/test/X86/Output/fix-branches-jrcxz.s.tmp.fdata
/home/sameeran/workspace/toolchain/bolt_development/BOLT/build/tools/bolt/test/X86/Output/fix-branches-jrcxz.s.script: line 6: 15114 Aborted                 (core dumped) /home/sameeran/workspace/toolchain/bolt_development/BOLT/build/bin/llvm-bolt /home/sameeran/workspace/toolchain/bolt_development/BOLT/build/tools/bolt/test/X86/Output/fix-branches-jrcxz.s.tmp.exe -relocs=1 -reorder-blocks=cache+ -print-finalized -o /home/sameeran/workspace/toolchain/bolt_development/BOLT/build/tools/bolt/test/X86/Output/fix-branches-jrcxz.s.tmp.out -data /home/sameeran/workspace/toolchain/bolt_development/BOLT/build/tools/bolt/test/X86/Output/fix-branches-jrcxz.s.tmp.fdata
     15115 Done                    | /home/sameeran/workspace/toolchain/bolt_development/BOLT/build/bin/FileCheck /home/sameeran/workspace/toolchain/bolt_development/BOLT/bolt/test/X86/fix-branches-jrcxz.s

--

```

Is it only me seeing the issue due to specific version of compiler?

**Comment by yota9** [comment]
@Sameeranjoshi No problems. 
I've got gcc 10.2.0 and I don't have such problem. Check if your binary has ".text" section, maybe your ld has some kind of custom linking script for example which renames section, I'm not sure why this assert could be raised without looking at the binary.. Might be Facebook engineers could help :)

**Comment by rafaelauler** [comment]
Hi @yota9 thanks for submitting this fix!

Regarding what @Sameeranjoshi observed, I've seen this problem before. fix-branches-jrcxz is a test that crashes in that way when BOLT fails to process the input binary.

I think BOLT should be fixed to handle that gracefully without crashing, but that's a separate discussion.

But I'm also curious to understand why -no-pie is enough to cause the test to crash in some machines but not in others.

I'll try to repro this bug in my machine.

Some background on our tests:

I think we are in an unfortunate position at the moment of depending on the host toolchain to generate inputs to our tests. I want to work to fix that and improve the way we do testing, but that's a future project. Because of this limitation, inputs to our tests may fail or not depending on which compiler was used to build BOLT. Who knows what the default driver invocation will add to the binary before it is fed to BOLT. It will at the very least try to link whatever version of the standard library is installed in the system, and that sometimes may be enough to change the binary in a way that breaks one test.

Because of that, we should try to use the least we can of the host toolchain (host_cxx etc), to make our tests depend solely on llvm-mc and other tools that we have control over and are in our repo. The only real reason we use host_cxx is because we don't have a linker (and we don't want to build or depend on lld), but that might change in the future.

**Comment by yota9** [comment]
@rafaelauler  No problems, thank you!
But jow did you see that -no-pie makes this test crash? I mean on the machines, where no-pie is the default test will work without my patch. On machines where ld expects PIE objects to link we need to pass -no-pie to be able at least to link it, without this patch it won't even be able to create executable.. So I don't see the connection between the -no-pie option and the crash.. Maybe it is related to some kind of other issue? It is interesting to investigate, but I'm unable to reproduce this :(

**Comment by rafaelauler** [comment]
Maybe @Sameeranjoshi could elaborate on which compiler was used to produce that crash?

**Comment by Sameeranjoshi** [comment]
I am using default compilers which come with Ubuntu 18.04(Bionic Beaver)
```
 $ c++ -v
Using built-in specs.
COLLECT_GCC=c++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.5.0-3ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin **--enable-default-pie** --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04)
```

**Comment by Sameeranjoshi** [comment]
Previous discussion where the issues was seen first.
https://github.com/facebookincubator/BOLT/pull/143#discussion_r620594992

**Comment by yota9** [comment]
Checked with 7.5.0 on ubuntu 20.10 - All tests are OK.
@rafaelauler @maksfb I think the -no-pie option is not the reason of test fault. Maybe we can merge this commit and open another issue for the problem above? Thank you!

**Comment by rafaelauler** [comment]
OK, I'll import it for internal review (trigger our CI) to see if tests succeed. If tests are all passing, all merge it.

**Comment by yota9** [comment]
@rafaelauler I think we may close this PR? Thank you!

**Comment by aaupov** [comment]
Merged it with 42aac5da3f25d0767622c18b01ad7895085a8810

**Pull request closed without merging**
